[package]
name = "tutorial"
version = "0.1.0"
authors = ["shaipe <shaipe@sina.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"

[dependencies.nickel]
version = "*"